### ISSUE TITLE
[Android]: issue on build

### ISSUE THREAD

**Issue by SuperBesse** [bamlab/react-native-batch-push#38] opened 2020-02-16 14:17 UTC
```
* What went wrong:
A problem occurred configuring project ':@bam.tech/react-native-batch'.
> The project name '@bam.tech/react-native-batch' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/5.5/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
```

Any idea to fix this issue on android ? Everything works on ios.

**Comment by leoz2007** [comment] 2020-02-25 17:17
Hello SuperBesse,
did you find a solution?

**Comment by leoz2007** [comment] 2020-02-25 17:17
Hello SuperBesse,
did you find a solution?

**Comment by SuperBesse** [comment] 2020-03-02 09:49
Unfortunately no :(

**Comment by ahmadrezaM97** [comment] 2020-03-02 11:35
did you find a solution? :(

**Comment by leoz2007** [comment] 2020-03-03 10:28
Not yet :(
I also had another problem on IOS.
When you install the npm package, the podspec file aren't find.

Add ios directory on your Podfile path for RNBatchPush

pod 'RNBatchPush',: path => "../node_modules/@bam.tech/react-native-batch/**ios**"

Maybe we have the same kind of error with android ?

**Comment by jasondibenedetto** [comment] 2020-03-17 00:22
Also having this issue

**Comment by leoz2007** [comment] 2020-03-31 08:28
Anyone find a solution?

**Comment by jasondibenedetto** [comment] 2020-04-15 00:35
@Minishlink @yleflour any progress on this one? Currently blocking react-native 0.61 upgrade.

Is the solution at this point to fork and rename the android package?

**Comment by yleflour** [comment] 2020-04-21 08:23
Will be looking into it tomorrow

**Comment by Nevosis** [comment] 2020-04-21 12:23
I made a PR changing the package name and android app name to @bam.tech_react-native-batch :
https://github.com/bamlab/react-native-batch-push/pull/44

**Comment by Nevosis** [comment] 2020-04-21 14:42
The issue is only on RN 0.61, it work properly on 0.62.
I suggest you guys just update your RN to 0.62, explanations :


The react native community android cli used in react-native 0.61 name the module based on its package.json name. And it doesn't work properly with package name containing dots.

(the line : name.replaceAll('^@([\w-]+)/', '$1_') didnt replace @bam.tech/react-native-batch to @bam.tech_react-native-batch)
They replaced it : https://github.com/react-native-community/cli/commit/3f37b390d62ef37302ac211b12f1eb0c62b7b814#diff-375026a0607eb034a6fc70cca7d74689

**Comment by yleflour** [comment] 2020-04-21 15:48
Thank you so much for investigating the issue. I will be closing the issue and PR then. If anyone requires 0.61, please use [patch-package](https://github.com/ds300/patch-package#readme) to apply the fix provided by @Nevosis

**Closed as completed by yleflour** 2020-04-21 15:48 UTC
